server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: spring-authorization-server
  security:
    user:
      name: user1
      password: password